# Generated by Django 2.2.6 on 2022-09-05 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='myprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='myprofile',
            name='last_name',
        ),
    ]
