# Generated by Django 4.1.1 on 2022-09-20 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myprofile", "0003_alter_myprofile_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="myprofile",
            options={},
        ),
    ]
